/* common word arrays, the word count is the first element */

char *cwSMART[572] = {"571", "a", "a's", "able", "about", "above", "according",
		      "accordingly", "across", "actually", "after", "afterwards",
		      "again", "against", "ain't", "all", "allow", "allows",
		      "almost", "alone", "along", "already", "also", "although",
		      "always", "am", "among", "amongst", "an", "and", "another",
		      "any", "anybody", "anyhow", "anyone", "anything", "anyway",
		      "anyways", "anywhere", "apart", "appear", "appreciate",
		      "appropriate", "are", "aren't", "around", "as", "aside",
		      "ask", "asking", "associated", "at", "available", "away",
		      "awfully", "b", "be", "became", "because", "become",
		      "becomes", "becoming", "been", "before", "beforehand",
		      "behind", "being", "believe", "below", "beside", "besides",
		      "best", "better", "between", "beyond", "both", "brief",
		      "but", "by", "c", "c'mon", "c's", "came", "can", "can't",
		      "cannot", "cant", "cause", "causes", "certain", "certainly",
		      "changes", "clearly", "co", "com", "come", "comes",
		      "concerning", "consequently", "consider", "considering",
		      "contain", "containing", "contains", "corresponding",
		      "could", "couldn't", "course", "currently", "d",
		      "definitely", "described", "despite", "did", "didn't",
		      "different", "do", "does", "doesn't", "doing", "don't",
		      "done", "down", "downwards", "during", "e", "each", "edu",
		      "eg", "eight", "either", "else", "elsewhere", "enough",
		      "entirely", "especially", "et", "etc", "even", "ever",
		      "every", "everybody", "everyone", "everything",
		      "everywhere", "ex", "exactly", "example", "except", "f",
		      "far", "few", "fifth", "first", "five", "followed",
		      "following", "follows", "for", "former", "formerly",
		      "forth", "four", "from", "further", "furthermore", "g",
		      "get", "gets", "getting", "given", "gives", "go", "goes",
		      "going", "gone", "got", "gotten", "greetings", "h", "had",
		      "hadn't", "happens", "hardly", "has", "hasn't", "have",
		      "haven't", "having", "he", "he's", "hello", "help", "hence",
		      "her", "here", "here's", "hereafter", "hereby", "herein",
		      "hereupon", "hers", "herself", "hi", "him", "himself",
		      "his", "hither", "hopefully", "how", "howbeit", "however",
		      "i", "i'd", "i'll", "i'm", "i've", "ie", "if", "ignored",
		      "immediate", "in", "inasmuch", "inc", "indeed", "indicate",
		      "indicated", "indicates", "inner", "insofar", "instead",
		      "into", "inward", "is", "isn't", "it", "it'd", "it'll",
		      "it's", "its", "itself", "j", "just", "k", "keep", "keeps",
		      "kept", "know", "knows", "known", "l", "last", "lately",
		      "later", "latter", "latterly", "least", "less", "lest",
		      "let", "let's", "like", "liked", "likely", "little", "look",
		      "looking", "looks", "ltd", "m", "mainly", "many", "may",
		      "maybe", "me", "mean", "meanwhile", "merely", "might",
		      "more", "moreover", "most", "mostly", "much", "must", "my",
		      "myself", "n", "name", "namely", "nd", "near", "nearly",
		      "necessary", "need", "needs", "neither", "never",
		      "nevertheless", "new", "next", "nine", "no", "nobody",
		      "non", "none", "noone", "nor", "normally", "not", "nothing",
		      "novel", "now", "nowhere", "o", "obviously", "of", "off",
		      "often", "oh", "ok", "okay", "old", "on", "once", "one",
		      "ones", "only", "onto", "or", "other", "others",
		      "otherwise", "ought", "our", "ours", "ourselves", "out",
		      "outside", "over", "overall", "own", "p", "particular",
		      "particularly", "per", "perhaps", "placed", "please",
		      "plus", "possible", "presumably", "probably", "provides",
		      "q", "que", "quite", "qv", "r", "rather", "rd", "re",
		      "really", "reasonably", "regarding", "regardless",
		      "regards", "relatively", "respectively", "right", "s",
		      "said", "same", "saw", "say", "saying", "says", "second",
		      "secondly", "see", "seeing", "seem", "seemed", "seeming",
		      "seems", "seen", "self", "selves", "sensible", "sent",
		      "serious", "seriously", "seven", "several", "shall", "she",
		      "should", "shouldn't", "since", "six", "so", "some",
		      "somebody", "somehow", "someone", "something", "sometime",
		      "sometimes", "somewhat", "somewhere", "soon", "sorry",
		      "specified", "specify", "specifying", "still", "sub",
		      "such", "sup", "sure", "t", "t's", "take", "taken", "tell",
		      "tends", "th", "than", "thank", "thanks", "thanx", "that",
		      "that's", "thats", "the", "their", "theirs", "them",
		      "themselves", "then", "thence", "there", "there's",
		      "thereafter", "thereby", "therefore", "therein", "theres",
		      "thereupon", "these", "they", "they'd", "they'll",
		      "they're", "they've", "think", "third", "this", "thorough",
		      "thoroughly", "those", "though", "three", "through",
		      "throughout", "thru", "thus", "to", "together", "too",
		      "took", "toward", "towards", "tried", "tries", "truly",
		      "try", "trying", "twice", "two", "u", "un", "under",
		      "unfortunately", "unless", "unlikely", "until", "unto",
		      "up", "upon", "us", "use", "used", "useful", "uses",
		      "using", "usually", "uucp", "v", "value", "various", "very",
		      "via", "viz", "vs", "w", "want", "wants", "was", "wasn't",
		      "way", "we", "we'd", "we'll", "we're", "we've", "welcome",
		      "well", "went", "were", "weren't", "what", "what's",
		      "whatever", "when", "whence", "whenever", "where",
		      "where's", "whereafter", "whereas", "whereby", "wherein",
		      "whereupon", "wherever", "whether", "which", "while",
		      "whither", "who", "who's", "whoever", "whole", "whom",
		      "whose", "why", "will", "willing", "wish", "with", "within",
		      "without", "won't", "wonder", "would", "would", "wouldn't",
		      "x", "y", "yes", "yet", "you", "you'd", "you'll", "you're",
		      "you've", "your", "yours", "yourself", "yourselves", "z",
		      "zero"};

char *cwLucene[34] = {"33", "a", "an", "and", "are", "as", "at", "be", "but", "by",
		      "for", "if", "in", "into", "is", "it", "no", "not", "of",
		      "on", "or", "such", "that", "the", "their", "then", "there",
		      "these", "they", "this", "to", "was", "will", "with"};

char *cwSER[18] = {"17", "a", "the", "an", "at", "by", "into", "on", "for", "from",
		   "to", "with", "of", "and", "or", "in", "not", "et"};

char *cwIndri[419] = {"418", "a", "about", "above", "according", "across", "after",
		      "afterwards", "again", "against", "albeit", "all", "almost",
		      "alone", "along", "already", "also", "although", "always",
		      "am", "among", "amongst", "an", "and", "another", "any",
		      "anybody", "anyhow", "anyone", "anything", "anyway",
		      "anywhere", "apart", "are", "around", "as", "at", "av",
		      "be", "became", "because", "become", "becomes", "becoming",
		      "been", "before", "beforehand", "behind", "being", "below",
		      "beside", "besides", "between", "beyond", "both", "but",
		      "by", "can", "cannot", "canst", "certain", "cf", "choose",
		      "contrariwise", "cos", "could", "cu", "day", "do", "does",
		      "doesn't", "doing", "dost", "doth", "double", "down",
		      "dual", "during", "each", "either", "else", "elsewhere",
		      "enough", "et", "etc", "even", "ever", "every", "everybody",
		      "everyone", "everything", "everywhere", "except",
		      "excepted", "excepting", "exception", "exclude",
		      "excluding", "exclusive", "far", "farther", "farthest",
		      "few", "ff", "first", "for", "formerly", "forth", "forward",
		      "from", "front", "further", "furthermore", "furthest",
		      "get", "go", "had", "halves", "hardly", "has", "hast",
		      "hath", "have", "he", "hence", "henceforth", "her", "here",
		      "hereabouts", "hereafter", "hereby", "herein", "hereto",
		      "hereupon", "hers", "herself", "him", "himself", "hindmost",
		      "his", "hither", "hitherto", "how", "however", "howsoever",
		      "i", "ie", "if", "in", "inasmuch", "inc", "include",
		      "included", "including", "indeed", "indoors", "inside",
		      "insomuch", "instead", "into", "inward", "inwards", "is",
		      "it", "its", "itself", "just", "kind", "kg", "km", "last",
		      "latter", "latterly", "less", "lest", "let", "like",
		      "little", "ltd", "many", "may", "maybe", "me", "meantime",
		      "meanwhile", "might", "moreover", "most", "mostly", "more",
		      "mr", "mrs", "ms", "much", "must", "my", "myself", "namely",
		      "need", "neither", "never", "nevertheless", "next", "no",
		      "nobody", "none", "nonetheless", "noone", "nope", "nor",
		      "not", "nothing", "notwithstanding", "now", "nowadays",
		      "nowhere", "of", "off", "often", "ok", "on", "once", "one",
		      "only", "onto", "or", "other", "others", "otherwise",
		      "ought", "our", "ours", "ourselves", "out", "outside",
		      "over", "own", "per", "perhaps", "plenty", "provide",
		      "quite", "rather", "really", "round", "said", "sake",
		      "same", "sang", "save", "saw", "see", "seeing", "seem",
		      "seemed", "seeming", "seems", "seen", "seldom", "selves",
		      "sent", "several", "shalt", "she", "should", "shown",
		      "sideways", "since", "slept", "slew", "slung", "slunk",
		      "smote", "so", "some", "somebody", "somehow", "someone",
		      "something", "sometime", "sometimes", "somewhat",
		      "somewhere", "spake", "spat", "spoke", "spoken", "sprang",
		      "sprung", "stave", "staves", "still", "such", "supposing",
		      "than", "that", "the", "thee", "their", "them",
		      "themselves", "then", "thence", "thenceforth", "there",
		      "thereabout", "thereabouts", "thereafter", "thereby",
		      "therefore", "therein", "thereof", "thereon", "thereto",
		      "thereupon", "these", "they", "this", "those", "thou",
		      "though", "thrice", "through", "throughout", "thru", "thus",
		      "thy", "thyself", "till", "to", "together", "too", "toward",
		      "towards", "ugh", "unable", "under", "underneath", "unless",
		      "unlike", "until", "up", "upon", "upward", "upwards", "us",
		      "use", "used", "using", "very", "via", "vs", "want", "was",
		      "we", "week", "well", "were", "what", "whatever",
		      "whatsoever", "when", "whence", "whenever", "whensoever",
		      "where", "whereabouts", "whereafter", "whereas", "whereat",
		      "whereby", "wherefore", "wherefrom", "wherein", "whereinto",
		      "whereof", "whereon", "wheresoever", "whereto", "whereunto",
		      "whereupon", "wherever", "wherewith", "whether", "whew",
		      "which", "whichever", "whichsoever", "while", "whilst",
		      "whither", "who", "whoa", "whoever", "whole", "whom",
		      "whomever", "whomsoever", "whose", "whosoever", "why",
		      "will", "wilt", "with", "within", "without", "worse",
		      "worst", "would", "wow", "ye", "yet", "year", "yippee",
		      "you", "your", "yours", "yourself", "yourselves"};

char *cwTerrier[734] = {"733", "x", "y", "your", "yours", "yourself", "yourselves", "you",
			"yond", "yonder", "yon", "ye", "yet", "z", "zillion", "j",
			"u", "umpteen", "usually", "us", "username", "uponed",
			"upons", "uponing", "upon", "ups", "upping", "upped", "up",
			"unto", "until", "unless", "unlike", "unliker", "unlikest",
			"under", "underneath", "use", "used", "usedest", "r",
			"rath", "rather", "rathest", "rathe", "re", "relate",
			"related", "relatively", "regarding", "really", "res",
			"respecting", "respectively", "q", "quite", "que", "qua",
			"n", "neither", "neaths", "neath", "nethe", "nethermost",
			"necessary", "necessariest", "necessarier", "never",
			"nevertheless", "nigh", "nighest", "nigher", "nine",
			"noone", "nobody", "nobodies", "nowhere", "nowheres", "no",
			"noes", "nor", "nos", "no-one", "none", "not",
			"notwithstanding", "nothings", "nothing", "nathless",
			"natheless", "t", "ten", "tills", "till", "tilled",
			"tilling", "to", "towards", "toward", "towardest",
			"towarder", "together", "too", "thy", "thyself", "thus",
			"than", "that", "those", "thou", "though", "thous",
			"thouses", "thoroughest", "thorougher", "thorough",
			"thoroughly", "thru", "thruer", "thruest", "thro",
			"through", "throughout", "throughest", "througher", "thine",
			"this", "thises", "they", "thee", "the", "then", "thence",
			"thenest", "thener", "them", "themselves", "these",
			"therer", "there", "thereby", "therest", "thereafter",
			"therein", "thereupon", "therefore", "their", "theirs",
			"thing", "things", "three", "two", "o", "oh", "owt",
			"owning", "owned", "own", "owns", "others", "other",
			"otherwise", "otherwisest", "otherwiser", "of", "often",
			"oftener", "oftenest", "off", "offs", "offest", "one",
			"ought", "oughts", "our", "ours", "ourselves", "ourself",
			"out", "outest", "outed", "outwith", "outs", "outside",
			"over", "overallest", "overaller", "overalls", "overall",
			"overs", "or", "orer", "orest", "on", "oneself", "onest",
			"ons", "onto", "a", "atween", "at", "athwart", "atop",
			"afore", "afterward", "afterwards", "after", "afterest",
			"afterer", "ain", "an", "any", "anything", "anybody",
			"anyone", "anyhow", "anywhere", "anent", "anear", "and",
			"andor", "another", "around", "ares", "are", "aest", "aer",
			"against", "again", "accordingly", "abaft", "abafter",
			"abaftest", "abovest", "above", "abover", "abouter",
			"aboutest", "about", "aid", "amidst", "amid", "among",
			"amongst", "apartest", "aparter", "apart", "appeared",
			"appears", "appear", "appearing", "appropriating",
			"appropriate", "appropriatest", "appropriates",
			"appropriater", "appropriated", "already", "always", "also",
			"along", "alongside", "although", "almost", "all", "allest",
			"aller", "allyou", "alls", "albeit", "awfully", "as",
			"aside", "asides", "aslant", "ases", "astrider", "astride",
			"astridest", "astraddlest", "astraddler", "astraddle",
			"availablest", "availabler", "available", "aughts", "aught",
			"vs", "v", "variousest", "variouser", "various", "via",
			"vis-a-vis", "vis-a-viser", "vis-a-visest", "viz", "very",
			"veriest", "verier", "versus", "k", "g", "go", "gone",
			"good", "got", "gotta", "gotten", "get", "gets", "getting",
			"b", "by", "byandby", "by-and-by", "bist", "both", "but",
			"buts", "be", "beyond", "because", "became", "becomes",
			"become", "becoming", "becomings", "becominger",
			"becomingest", "behind", "behinds", "before", "beforehand",
			"beforehandest", "beforehander", "bettered", "betters",
			"better", "bettering", "betwixt", "between", "beneath",
			"been", "below", "besides", "beside", "m", "my", "myself",
			"mucher", "muchest", "much", "must", "musts", "musths",
			"musth", "main", "make", "mayest", "many", "mauger",
			"maugre", "me", "meanwhiles", "meanwhile", "mostly", "most",
			"moreover", "more", "might", "mights", "midst", "midsts",
			"h", "huh", "humph", "he", "hers", "herself", "her",
			"hereby", "herein", "hereafters", "hereafter", "hereupon",
			"hence", "hadst", "had", "having", "haves", "have", "has",
			"hast", "hardly", "hae", "hath", "him", "himself", "hither",
			"hitherest", "hitherer", "his", "how-do-you-do", "however",
			"how", "howbeit", "howdoyoudo", "hoos", "hoo", "w",
			"woulded", "woulding", "would", "woulds", "was", "wast",
			"we", "wert", "were", "with", "withal", "without", "within",
			"why", "what", "whatever", "whateverer", "whateverest",
			"whatsoeverer", "whatsoeverest", "whatsoever", "whence",
			"whencesoever", "whenever", "whensoever", "when", "whenas",
			"whether", "wheen", "whereto", "whereupon", "wherever",
			"whereon", "whereof", "where", "whereby", "wherewithal",
			"wherewith", "whereinto", "wherein", "whereafter",
			"whereas", "wheresoever", "wherefrom", "which", "whichever",
			"whichsoever", "whilst", "while", "whiles", "whithersoever",
			"whither", "whoever", "whosoever", "whoso", "whose",
			"whomever", "s", "syne", "syn", "shalling", "shall",
			"shalled", "shalls", "shoulding", "should", "shoulded",
			"shoulds", "she", "sayyid", "sayid", "said", "saider",
			"saidest", "same", "samest", "sames", "samer", "saved",
			"sans", "sanses", "sanserifs", "sanserif", "so", "soer",
			"soest", "sobeit", "someone", "somebody", "somehow", "some",
			"somewhere", "somewhat", "something", "sometimest",
			"sometimes", "sometimer", "sometime", "several",
			"severaler", "severalest", "serious", "seriousest",
			"seriouser", "senza", "send", "sent", "seem", "seems",
			"seemed", "seemingest", "seeminger", "seemings", "seven",
			"summat", "sups", "sup", "supping", "supped", "such",
			"since", "sine", "sines", "sith", "six", "stop", "stopped",
			"p", "plaintiff", "plenty", "plenties", "please", "pleased",
			"pleases", "per", "perhaps", "particulars", "particularly",
			"particular", "particularest", "particularer", "pro",
			"providing", "provides", "provided", "provide", "probably",
			"l", "layabout", "layabouts", "latter", "latterest",
			"latterer", "latterly", "latters", "lots", "lotting",
			"lotted", "lot", "lest", "less", "ie", "ifs", "if", "i",
			"info", "information", "itself", "its", "it", "is", "idem",
			"idemer", "idemest", "immediate", "immediately",
			"immediatest", "immediater", "in", "inwards", "inwardest",
			"inwarder", "inward", "inasmuch", "into", "instead",
			"insofar", "indicates", "indicated", "indicate",
			"indicating", "indeed", "inc", "f", "fact", "facts", "fs",
			"figupon", "figupons", "figuponing", "figuponed", "few",
			"fewer", "fewest", "frae", "from", "failing", "failings",
			"five", "furthers", "furtherer", "furthered", "furtherest",
			"further", "furthering", "furthermore", "fourscore",
			"followthrough", "for", "forwhy", "fornenst", "formerly",
			"former", "formerer", "formerest", "formers", "forbye",
			"forby", "fore", "forever", "forer", "fores", "four", "d",
			"ddays", "dday", "do", "doing", "doings", "doe", "does",
			"doth", "downwarder", "downwardest", "downward",
			"downwards", "downs", "done", "doner", "dones", "donest",
			"dos", "dost", "did", "differentest", "differenter",
			"different", "describing", "describe", "describes",
			"described", "despiting", "despites", "despited", "despite",
			"during", "c", "cum", "circa", "chez", "cer", "certain",
			"certainest", "certainer", "cest", "canst", "cannot",
			"cant", "cants", "canting", "cantest", "canted", "co",
			"could", "couldst", "comeon", "comeons", "come-ons",
			"come-on", "concerning", "concerninger", "concerningest",
			"consequently", "considering", "e", "eg", "eight", "either",
			"even", "evens", "evenser", "evensest", "evened", "evenest",
			"ever", "everyone", "everything", "everybody", "everywhere",
			"every", "ere", "each", "et", "etc", "elsewhere", "else",
			"ex", "excepted", "excepts", "except", "excepting", "exes",
			"enough"};
